#! /usr/bin/env python3
# encoding: utf-8

def options(opt):
    pass

def configure(conf):
    pass

from os.path import join
def build(bld):
    common_includes = bld.user_vars['common_includes'] + [join(bld.top_dir, 'include', 'server')]
    common_lib = bld.user_vars['common_lib']
