#! /usr/bin/env python3
# encoding: utf-8

def options(opt):
    pass

def configure(conf):
    pass

from os.path import join
def build(bld):
    common_includes = bld.user_vars['common_includes'] + [join(bld.top_dir, 'include', 'shared')]
    bld.objects(source=['Position.cxx'],
                target='Position',
                includes=common_includes,
               )

