#! /usr/bin/env python3
# encoding: utf-8

def options(opt):
    pass

def configure(conf):
    pass

from os.path import join
def build(bld):
    sdl_libs = ['SDL', 'SDL_image']
    allegro_libs = ['allegro', 'allegro_image']
    common_includes = ['.', '/usr/include/', join(bld.top_dir, 'include/')]
    bld.program(
                source = 'allegro_main.c', 
                target = 'allegro_main', 
                lib = allegro_libs, 
                includes = common_includes, 
                )
    bld.program(
                source = 'sdl_main.c', 
                target = 'sdl_main', 
                lib = sdl_libs,
                includes = common_includes, 
                )
    bld.program(
                source = 'sdl_main.cxx', 
                target = 'sdl_main_cxx', 
                lib = sdl_libs,
                includes = common_includes, 
                )
    bld.program(
                source = ['server_main.cpp','ClientAccepter.cpp','PacketTransporter.cpp','packet.cpp'],
                target = 'server_main',
                lib = ['boost_thread','SDL_net'],
                )
    bld.program(
                source = ['client_main.cpp','network_connector.cpp','PacketTransporter.cpp','packet.cpp'],
                target = 'client_main',
                lib = ['boost_thread','SDL_net'],
                )
