#! /usr/bin/env python3
# encoding: utf-8

def options(opt):
    pass

def configure(conf):
    pass

from os.path import join
def build(bld):
    sdl_libs = ['SDL', 'SDL_image']
    allegro_libs = ['allegro', 'allegro_image']
    common_includes = ['.',
                       join(bld.top_dir, 'deps', 'usr', 'local', 'include'),
                       join(bld.top_dir, 'include'),
                       join(bld.top_dir, 'include', 'shared')]
    in_repo_libpath = join(bld.top_dir, 'deps', 'usr', 'local', 'lib')
    common_libpath = [in_repo_libpath]
    client_includes = common_includes + [join(bld.top_dir, 'include', 'client')]
    server_includes = common_includes + [join(bld.top_dir, 'include', 'server')]
    common_lib = ['boost_system', 'boost_thread', 'SDL_net', 'SDL' ]
    #common_lib = ['boost_system', 'boost_thread', 'boost_timer', #'boost_chrono', 'SDL_net']
    server_lib = common_lib
    server_defines = ['SERVER_SIDE']
    client_defines = ['CLIENT_SIDE']
    bld.stlib(
        source = bld.path.ant_glob('shared/*.cxx'),
        includes = client_includes,
        defines = client_defines,
        target = 'angel-stage-shared-client-lib',
        )
    bld.stlib(
        source = bld.path.ant_glob('client/*.cxx'),
        includes = client_includes,
        defines = client_defines,
        use = 'angel-stage-shared-client-lib',
        target = 'angel-stage-client-lib',
        )
    bld.program(
        source = 'client_main.cxx',
        target = 'client_main',
        includes = client_includes,
        defines = client_defines,
        libpath = common_libpath,
        lib = common_lib + allegro_libs,
        use = ['angel-stage-shared-client-lib', 'angel-stage-client-lib'],
        linkflags='-Wl,-R ' + in_repo_libpath,
        )
    bld.stlib(
        source = bld.path.ant_glob('shared/*.cxx'),
        includes = server_includes,
        defines = server_defines,
        target = 'angel-stage-shared-server-lib',
        )
    bld.stlib(
        source = bld.path.ant_glob('server/*.cxx'),
        includes = server_includes,
        use = 'angel-stage-shared-server-lib',
        target = 'angel-stage-server-lib',
        defines = server_defines,
        )
    bld.program(
        source = 'server_main.cxx',
        target = 'server_main',
        includes = server_includes,
        lib = server_lib,
        libpath = common_libpath,
        use = ['angel-stage-shared-server-lib', 'angel-stage-server-lib'],
        defines = server_defines,
        linkflags='-Wl,-R ' + in_repo_libpath,
        )
